const EVENT_TYPES = {
  DAY_CREATED: "DAY_CREATED",
  DAY_CLOSED: "DAY_CLOSED",
  USER_ONBOARDED: "USER_ONBOARDED",
  LEARNING_TOPIC_PROGRESS_UPDATED: "LEARNING_TOPIC_PROGRESS_UPDATED",
};

const EVENT_CATEGORIES = {
  DAY_LIFECYCLE: "DAY_LIFECYCLE",
  USER: "USER",
  LEARNING: "LEARNING",
};

module.exports = { EVENT_TYPES, EVENT_CATEGORIES };
