const EVENT_TYPES = {
  DAY_CREATED: 'DAY_CREATED',
  DAY_CLOSED: 'DAY_CLOSED',
  USER_ONBOARDED: 'USER_ONBOARDED',
};

const EVENT_CATEGORIES = {
  DAY_LIFECYCLE: 'DAY_LIFECYCLE',
  USER: 'USER',
};

module.exports = { EVENT_TYPES, EVENT_CATEGORIES };
